=== CESGA-Quantum-Spain/cunqa/cunqa/json_schema/calibrations_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "calibrations",
    "title": "CalibrationsFile",
    "description": "Json schema for the calibration file used to model the QPU noise",
    "type": "object",
    "properties": 
    {
        "Qubits":
        {
            "description": "Qubits calibrations",
            "type" : "object",
            "properties":
            {
                "type":
                {
                    "type": "object",
                    "properties":
                    {
                        "T1":
                        {
                            "description": "",
                            "type":"number"
                        },
                        "T2e":
                        {
                            "description": "",
                            "type":"number"
                        },
                        "Drive Frequency ":
                        {
                            "description": "",
                            "type":"number"
                        },
                        "Measuring frequency":
                        {
                            "description": "",
                            "type":"number"
                        },
                        "Measuring time":
                        {
                            "description": "",
                            "type":"number"
                        },
                        "Fidelity init":
                        {
                            "description": "",
                            "type":"number"
                        },
                        "Fidelity readout":
                        {
                            "description": "",
                            "type":"number"
                        },
                        "Drive Frequency":
                        {
                            "description": "",
                            "type":"number"
                        },
                        "Readout duration":
                        {
                            "description": "",
                            "type":"number"
                        },
                        "T1 (s)":
                        {
                            "description": "",
                            "type":"number"
                        },
                        "T2 (s)":
                        {
                            "description": "",
                            "type":"number"
                        },
                        "Drive Frequency (Hz)":
                        {
                            "description": "",
                            "type":"number"
                        },
                        "Measuring Frequency (Hz)":
                        {
                            "description": "",
                            "type":"number"
                        },
                        "Readout duration (s)":
                        {
                            "description": "",
                            "type":"number"
                        },
                        "Measuring frequency (Hz)":
                        {   
                            "description": "",
                            "type":"number"
                        },
                        "Readout fidelity(RB)":
                        {
                            "description": "",
                            "type":"number"
                        }
                    }
                }
            }   
        },

        "Q1Gates":
        {
            "description": "Calibrations of one-qubit gates",
            "type": "object",
            "properties":
            {
                "type":
                {
                    "type":"object",
                    "properties":
                    {
                        "type": 
                        {
                            "type": "object",
                            "properties":
                            {
                                "type": 
                                {
                                    "type": "object",
                                    "properties":
                                    {
                                        "duration (ns)":
                                        {
                                            "description": "",
                                            "type":"number"
                                        },
                                        "Fidelity":
                                        {
                                            "description": "",
                                            "type":"number"
                                        },
                                        "Duration (ns)":
                                        {
                                            "description": "",
                                            "type":"number"
                                        },
                                        "Gate duration (s)":
                                        {
                                            "description": "",
                                            "type":"number"
                                        },
                                        "Fidelity(RB)":
                                        {
                                            "description": "",
                                            "type":"number"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },

        "Q2Gates":
        {
            "description": "Calibrations of two-qubits gates",
            "type": "object",
            "properties":
            {
                "type":
                {
                    "type":"object",
                    "properties":
                    {
                        "type": 
                        {
                            "type":"object",
                            "properties":
                            {
                                "Control":
                                {
                                    "description": "",
                                    "type":"integer"
                                },
                                "Target":
                                {
                                    "description": "",
                                    "type":"integer"
                                },
                                "Duration (s)":
                                {
                                    "description": "",
                                    "type":"number"
                                },
                                "Fidelity(RB)":
                                {
                                    "description": "",
                                    "type":"number"
                                }
                            }
                        }
                    }
                }
                
            }
        },

        "Q2Gates(RB)":
        {
            "description": "Calibrations of two-qubits gates",
            "type": "object",
            "properties":
            {
                "type":
                {
                    "type":"object",
                    "properties":
                    {
                        "type": 
                        {
                            "type":"object",
                            "properties":
                            {
                                "Control":
                                {
                                    "description": "",
                                    "type":"integer"
                                },
                                "Target":
                                {
                                    "description": "",
                                    "type":"integer"
                                },
                                "Duration (s)":
                                {
                                    "description": "",
                                    "type":"number"
                                },
                                "Fidelity(RB)":
                                {
                                    "description": "",
                                    "type":"number"
                                }
                            }
                        }
                    }
                }
                
            }
        }
    }
}

=== CESGA-Quantum-Spain/cunqa/examples/calibrations/calibration_file.json
{
   "Qubits": {
      "q[0]": {
         "Measuring frequency": 10276000000.0,
         "T1 (s)": 2.3857e-05,
         "T2 (s)": 3.6112e-05,
         "Drive Frequency (Hz)": 4372600000.0,
         "Measuring Frequency (Hz)": 10276000000.0,
         "Readout duration (s)": 2.8599e-06,
         "Measuring frequency (Hz)": 10277000000.0,
         "Readout fidelity(RB)": 0.6287
      },
      "q[1]": {
         "T1": 44.057,
         "T2e": 25.749,
         "Drive Frequency ": 4257400000.0,
         "Measuring frequency": 9652600000.0,
         "Measuring time": 0.005515,
         "Fidelity init": 0.933,
         "Fidelity readout": 0.9174,
         "Drive Frequency": 4257411225.1399617,
         "Readout duration": 5515.015015015015,
         "T1 (s)": 5.5039e-05,
         "T2 (s)": 3.3123e-05,
         "Drive Frequency (Hz)": 4257400000.0,
         "Measuring Frequency (Hz)": 9652600000.0,
         "Readout duration (s)": 6.7853e-06,
         "Measuring frequency (Hz)": 9652600000.0,
         "Readout fidelity(RB)": 0.9274
      },
      "q[2]": {
         "T1": 2611.1,
         "T2e": 160.96,
         "Drive Frequency ": 4369200000.0,
         "Measuring frequency": 10077000000.0,
         "Measuring time": 0.0056952,
         "Fidelity init": 0.851,
         "Fidelity readout": 0.8643,
         "Drive Frequency": 4369176489.942258,
         "Readout duration": 5695.195195195195,
         "T1 (s)": 6.6382e-05,
         "T2 (s)": 8.7695e-05,
         "Drive Frequency (Hz)": 4369200000.0,
         "Measuring Frequency (Hz)": 10077000000.0,
         "Readout duration (s)": 1.2e-05,
         "Measuring frequency (Hz)": 10077000000.0,
         "Readout fidelity(RB)": 0.8724
      },
      "q[3]": {
         "T1": 57.905,
         "T2e": 106.2,
         "Drive Frequency ": 4220000000.0,
         "Measuring frequency": 9850800000.0,
         "Measuring time": 0.0057032,
         "Fidelity init": 0.949,
         "Fidelity readout": 0.9177,
         "Drive Frequency": 4219992286.125655,
         "Readout duration": 7016.516516516515,
         "T1 (s)": 4.4893e-05,
         "T2 (s)": 0.00011292,
         "Drive Frequency (Hz)": 4220000000.0,
         "Measuring Frequency (Hz)": 9850800000.0,
         "Readout duration (s)": 5.968e-06,
         "Measuring frequency (Hz)": 9850800000.0,
         "Readout fidelity(RB)": 0.9131
      },
      "q[4]": {
         "T1": 39.806,
         "T2e": 59.079,
         "Drive Frequency ": 4340900000.0,
         "Measuring frequency": 9644900000.0,
         "Measuring time": 0.005,
         "Fidelity init": 0.772,
         "Fidelity readout": 0.7892,
         "Drive Frequency": 4340947930.728189,
         "Readout duration": 5000.0,
         "T1 (s)": 6.2614e-05,
         "T2 (s)": 0.00014265,
         "Drive Frequency (Hz)": 4340900000.0,
         "Measuring Frequency (Hz)": 9644900000.0,
         "Readout duration (s)": 5.3233e-06,
         "Measuring frequency (Hz)": 9644900000.0,
         "Readout fidelity(RB)": 0.801
      },
      "q[5]": {
         "T1": 71.91,
         "T2e": 82.617,
         "Drive Frequency ": 4398400000.0,
         "Measuring frequency": 9848200000.0,
         "Measuring time": 0.0042012,
         "Fidelity init": 0.885,
         "Fidelity readout": 0.887,
         "Drive Frequency": 4398416817.5094185,
         "Readout duration": 4201.201201201201,
         "T1 (s)": 8.1266e-05,
         "T2 (s)": 9.1296e-05,
         "Drive Frequency (Hz)": 4398400000.0,
         "Measuring Frequency (Hz)": 9848200000.0,
         "Readout duration (s)": 1.0791e-05,
         "Measuring frequency (Hz)": 9848300000.0,
         "Readout fidelity(RB)": 0.8872
      }
   },
   "Q1Gates": {
      "q[0]": {
         "SX": {
            "Gate duration (s)": 6.4e-08,
            "Fidelity(RB)": 0.99177
         },
         "Rz": {
            "duration (ns)": 0,
            "Fidelity": 100.0,
            "Fidelity(RB)": 1.0
         }
      },
      "q[1]": {
         "SX": {
            "Gate duration (s)": 3.2e-08,
            "Fidelity(RB)": 0.99849
         },
         "Rz": {
            "duration (ns)": 0,
            "Fidelity": 100.0,
            "Fidelity(RB)": 1.0
         }
      },
      "q[2]": {
         "SX": {
            "Gate duration (s)": 6.4e-08,
            "Fidelity(RB)": 0.9865
         },
         "Rz": {
            "duration (ns)": 0,
            "Fidelity": 100.0,
            "Fidelity(RB)": 1.0
         }
      },
      "q[3]": {
         "SX": {
            "Gate duration (s)": 3.2e-08,
            "Fidelity(RB)": 0.99715
         },
         "Rz": {
            "duration (ns)": 0,
            "Fidelity": 100.0,
            "Fidelity(RB)": 1.0
         }
      },
      "q[4]": {
         "SX": {
            "Gate duration (s)": 6.4e-08,
            "Fidelity(RB)": 0.99817
         },
         "Rz": {
            "duration (ns)": 0,
            "Fidelity": 100.0,
            "Fidelity(RB)": 1.0
         }
      },
      "q[5]": {
         "SX": {
            "Gate duration (s)": 3.2e-08,
            "Fidelity(RB)": 0.98555
         },
         "Rz": {
            "duration (ns)": 0,
            "Fidelity": 100.0,
            "Fidelity(RB)": 1.0
         }
      },
      "q[6]": {
         "SX": {
            "Gate duration (s)": 3.2e-08,
            "Fidelity(RB)": 0.99868
         },
         "Rz": {
            "duration (ns)": 0,
            "Fidelity": 100.0,
            "Fidelity(RB)": 1.0
         }
      },
      "q[7]": {
         "SX": {
            "Gate duration (s)": 1.28e-07,
            "Fidelity(RB)": 0.98904
         },
         "Rz": {
            "duration (ns)": 0,
            "Fidelity": 100.0,
            "Fidelity(RB)": 1.0
         }
      },
      "q[8]": {
         "SX": {
            "Gate duration (s)": 3.2e-08,
            "Fidelity(RB)": 0.99888
         },
         "Rz": {
            "duration (ns)": 0,
            "Fidelity": 100.0,
            "Fidelity(RB)": 1.0
         }
      },
      "q[9]": {
         "SX": {
            "Gate duration (s)": 6.4e-08,
            "Fidelity(RB)": 0.97257
         },
         "Rz": {
            "duration (ns)": 0,
            "Fidelity": 100.0,
            "Fidelity(RB)": 1.0
         }
      },
      "q[10]": {
         "SX": {
            "Gate duration (s)": 3.2e-08,
            "Fidelity(RB)": 0.999
         },
         "Rz": {
            "duration (ns)": 0,
            "Fidelity": 100.0,
            "Fidelity(RB)": 1.0
         }
      },
      "q[11]": {
         "SX": {
            "Gate duration (s)": 3.2e-08,
            "Fidelity(RB)": 0.99642
         },
         "Rz": {
            "duration (ns)": 0,
            "Fidelity": 100.0,
            "Fidelity(RB)": 1.0
         }
      },
      "q[12]": {
         "SX": {
            "Gate duration (s)": 3.2e-08,
            "Fidelity(RB)": 0.99717
         },
         "Rz": {
            "duration (ns)": 0,
            "Fidelity": 100.0,
            "Fidelity(RB)": 1.0
         }
      },
      "q[13]": {
         "SX": {

            "Gate duration (s)": 3.2e-08,
            "Fidelity(RB)": 0.99336
         },
         "Rz": {
            "duration (ns)": 0,
            "Fidelity": 100.0,
            "Fidelity(RB)": 1.0
         }
      },
      "q[14]": {
         "SX": {
            "Gate duration (s)": 3.2e-08,
            "Fidelity(RB)": 0.99901
         },
         "Rz": {
            "duration (ns)": 0,
            "Fidelity": 100.0,
            "Fidelity(RB)": 1.0
         }
      },
      "q[15]": {
         "SX": {
            "Gate duration (s)": 3.2e-08,
            "Fidelity(RB)": 0.99969
         },
         "Rz": {
            "duration (ns)": 0,
            "Fidelity": 100.0,
            "Fidelity(RB)": 1.0
         }
      },
      "q[16]": {
         "SX": {
            "Gate duration (s)": 3.2e-08,
            "Fidelity(RB)": 0.99971
         },
         "Rz": {
            "duration (ns)": 0,
            "Fidelity": 100.0,
            "Fidelity(RB)": 1.0
         }
      },
      "q[17]": {
         "SX": {
            "Gate duration (s)": 1.28e-07,
            "Fidelity(RB)": 0.99173
         },
         "Rz": {
            "duration (ns)": 0,
            "Fidelity": 100.0,
            "Fidelity(RB)": 1.0
         }
      },
      "q[18]": {
         "SX": {
            "Gate duration (s)": 3.2e-08,
            "Fidelity(RB)": 0.99574
         },
         "Rz": {
            "duration (ns)": 0,
            "Fidelity": 100.0,
            "Fidelity(RB)": 1.0
         }
      },
      "q[19]": {
         "SX": {
            "Gate duration (s)": 3.2e-08,
            "Fidelity(RB)": 0.99916
         },
         "Rz": {
            "duration (ns)": 0,
            "Fidelity": 100.0,
            "Fidelity(RB)": 1.0
         }
      },
      "q[20]": {
         "SX": {
            "Gate duration (s)": 3.2e-08,
            "Fidelity(RB)": 0.99956
         },
         "Rz": {
            "duration (ns)": 0,
            "Fidelity": 100.0,
            "Fidelity(RB)": 1.0
         }
      },
      "q[21]": {
         "SX": {
            "Gate duration (s)": 3.2e-08,
            "Fidelity(RB)": 0.99862
         },
         "Rz": {
            "duration (ns)": 0,
            "Fidelity": 100.0,
            "Fidelity(RB)": 1.0
         }
      },
      "q[22]": {
         "SX": {
            "Gate duration (s)": 3.2e-08,
            "Fidelity(RB)": 0.99914
         },
         "Rz": {
            "duration (ns)": 0,
            "Fidelity": 100.0,
            "Fidelity(RB)": 1.0
         }
      },
      "q[23]": {
         "SX": {
            "Gate duration (s)": 3.2e-08,
            "Fidelity(RB)": 0.99965
         },
         "Rz": {
            "duration (ns)": 0,
            "Fidelity": 100.0,
            "Fidelity(RB)": 1.0
         }
      },
      "q[24]": {
         "SX": {
            "Gate duration (s)": 3.2e-08,
            "Fidelity(RB)": 0.98128
         },
         "Rz": {
            "duration (ns)": 0,
